import React from 'react'

const RemoteSensing = () => {
  return (
    <div className='w-screen h-screen bg-[#F6F6F9] p-4'>
        <div className="container mx-auto flex items-center flex-col gap-10 p-4 bg-white shadow-lg rounded-2xl ">
            <h1 className='text-4xl font-semibold text-[#0F33A0]'>Remote Sensing</h1>
            <p>Uttar Pradesh was the first and foremost state in the country to establish the first state Remote Sensing Applications Centre, Uttar Pradesh (RSAC-UP) in May, 1982 at Lucknow. RSAC-UP has been utilizing the geospatial technologies of satellite remote sensing, Image Processing, GIS, GPS, LiDAR, Bathymetry, Customized Software Development using AI, ML, DL & AL methods in conjunction with geophysical surveys, soil and water testing techniques for assessment, monitoring, utilization and management of various natural resources of the state with a view to achieve sustainable development. With the passage of time this RSAC-UP has diversified its domain from natural resource management to infrastructure mapping and monitoring, utility mapping, disaster management, Software development and is also involved in training, capacity building and vocational educational programme on geospatial technologies such as running M. Tech in “Remote Sensing and GIS”. RSAC-UP is carrying out the work in crop area and production estimation of different crops, Space Based Information Support for Decentralized Planning, Wetland Inventory Assessment,  Monitoring of Integrated watershed, Monitoring Vulnerability Assessment, desertification and Land Degradation, Assessment of Plantation outside forest areas, Water Sector Restructuring, Unauthorized Colony Mapping with the area of Development Authorities of U.P., Asset Mapping, Ground Water Targeting, Rural Urban planning including smart city and infrastructure planning. Further the Centre is also working on pilot basis for the projects such as assessment of one district one crop, selection of cold storages for crop management, rejuvenation of alluvial rivers, disaster management, pilot studies on site suitability of suitable sites for rain water harvesting, fruit belt development, fodder crops and solid waste disposal etc. The Centre is also working on GIS mapping for schools, development and updation of satellite data and GIS based geoportal. Further, the Centre is imparting training on remote sensing applications to the officials of user departments and also to the faculty members and research scholars of Universities. M.Tech in Remote Sensing and GIS in affiliation with AKTU is also being run by RSAC-UP since 2013.</p>
        </div>
    </div>
  )
}

export default RemoteSensing